name: Status Servers Daily

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Run server
        uses: borales/actions-yarn@v5
        with:
          cmd: daily
        env: 
          SERVICOS: ${{ secrets.SERVICOS }}
          SECRET_UTALK: ${{ secrets.SECRET_UTALK }}
          LOCAIS: ${{ secrets.LOCAIS }}
