name: Status Servers Daily

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run install
        uses: borales/actions-yarn@v5
        with:
          cmd: install
      - name: Run server
        uses: borales/actions-yarn@v5
        with:
          cmd: daily
        env: 
          SERVICOS: ${{ secrets.SERVICOS }}
          LOCAIS: ${{ secrets.LOCAIS }}
          URL_WHATSAPP: ${{ secrets.URL_WHATSAPP }}
          WHATSAPP_API_SECRET: ${{ secrets.WHATSAPP_API_SECRET }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
